// Generated by CoffeeScript 1.6.3
var app, client, express, expressValidator, findLetterGrade, findRemoteAddress, gradeMap, port, rtg, setJsonResponseHeaders;

express = require("express");

app = express();

expressValidator = require('express-validator');

app.use(express.bodyParser());

app.use(expressValidator());

app.use(function(req, res, next) {
  var team_id;
  team_id = req.body.team_id;
  if ((team_id != null) && team_id !== 'tor') {
    return setJsonResponseHeaders(res, "Team not allowed.");
  } else {
    return next();
  }
});

if (process.env.REDISTOGO_URL) {
  rtg = require("url").parse(process.env.REDISTOGO_URL);
  client = require("redis").createClient(rtg.port, rtg.hostname);
  client.auth(rtg.auth.split(":")[1]);
} else {
  client = require("redis").createClient();
}

gradeMap = {
  'A+': 4,
  'A': 3.85,
  'A-': 3.7,
  'B+': 3.3,
  'B': 3,
  'B-': 2.7,
  'C+': 2.3,
  'C': 2,
  'C-': 1.7,
  'D+': 1.3,
  'D': 1,
  'D-': .7,
  'F': 0
};

findLetterGrade = function(numerical) {
  if ((4 >= numerical && numerical > 3.85)) {
    return 'A+';
  } else if ((3.85 >= numerical && numerical > 3.7)) {
    return 'A-';
  } else if ((3.7 >= numerical && numerical > 3.3)) {
    return 'A';
  } else if ((3.3 >= numerical && numerical > 3)) {
    return 'B+';
  } else if ((3 >= numerical && numerical > 2.7)) {
    return 'B';
  } else if ((2.7 >= numerical && numerical > 2.3)) {
    return 'B-';
  } else if ((2.3 >= numerical && numerical > 2)) {
    return 'C+';
  } else if ((2 >= numerical && numerical > 1.7)) {
    return 'C';
  } else if ((1.7 >= numerical && numerical > 1.3)) {
    return 'C-';
  } else if ((1.3 >= numerical && numerical > 1)) {
    return 'D+';
  } else if ((1 >= numerical && numerical > .7)) {
    return 'D';
  } else if ((.7 >= numerical && numerical > .5)) {
    return 'D-';
  } else if (numerical <= .5) {
    return 'F';
  } else {
    return null;
  }
};

findRemoteAddress = function(req) {
  var list, remote_address;
  remote_address = req.headers["x-forwarded-for"];
  if (remote_address != null) {
    list = remote_address.split(",");
    remote_address = list[0];
  } else {
    remote_address = req.connection.remoteAddress;
  }
  return remote_address.trim();
};

setJsonResponseHeaders = function(res, data) {
  res.header("content-type", "text/javascript");
  res.header("content-length", (data == null ? 0 : data.length));
  return res.end(data);
};

app.get("/mediator.html", function(req, res) {
  return res.sendfile("./mediator.html");
});

app.get("/client.min.js", function(req, res) {
  return res.sendfile("./client.js");
});

app.get("/mediator.min.js", function(req, res) {
  return res.sendfile("./mediator.js");
});

app.post("/rating", function(req, res) {
  var game_id, ip_address, team_id;
  team_id = req.body.team_id;
  game_id = req.body.game_id;
  ip_address = findRemoteAddress(req);
  return client.hvals("" + team_id + ":" + game_id, function(err, reply) {
    var active_game_key, ind, json, multi, r, results, user_vote_key, _i, _j, _len, _len1;
    results = new Array();
    for (_i = 0, _len = reply.length; _i < _len; _i++) {
      r = reply[_i];
      json = JSON.parse(r);
      json['grade'] = findLetterGrade(parseFloat(json['average']));
      results.push(json);
    }
    multi = client.multi();
    active_game_key = "active_game:" + game_id;
    multi.exists(active_game_key);
    for (ind = _j = 0, _len1 = results.length; _j < _len1; ind = ++_j) {
      r = results[ind];
      user_vote_key = "" + ip_address + ":" + game_id + ":" + r.player_id;
      multi.hexists("user_votes", user_vote_key);
    }
    return multi.exec(function(err, replies) {
      var allow_game_voting, i, _k, _len2, _ref;
      if (err != null) {
        console.log(err);
      }
      allow_game_voting = replies[0] === 1 || replies.length === 1;
      _ref = replies.slice(1);
      for (i = _k = 0, _len2 = _ref.length; _k < _len2; i = ++_k) {
        r = _ref[i];
        results[i]["allow_voting"] = replies[i] === 0;
      }
      results = JSON.stringify({
        "allow_game_voting": allow_game_voting,
        "grades": results
      });
      return setJsonResponseHeaders(res, results);
    });
  });
});

app.post("/vote", function(req, res) {
  var active_game_key, errors, game_id, grade, ip_address, outer_multi, player_id, player_key, team_id, user_vote_key;
  req.checkBody('team_id', 'Invalid Team ID').notEmpty();
  req.checkBody('game_id', 'Invalid Game ID').notEmpty().isInt();
  req.checkBody('player_id', 'Invalid Player ID').notEmpty();
  req.checkBody('player_grade', 'Invalid Player Grade').notEmpty();
  errors = req.validationErrors();
  if (errors) {
    res.status(400);
    setJsonResponseHeaders(res, JSON.stringify(errors));
    return;
  }
  team_id = req.body.team_id;
  game_id = req.body.game_id;
  player_id = req.body.player_id;
  grade = req.body.player_grade;
  ip_address = findRemoteAddress(req);
  if (!grade in gradeMap) {
    res.status(506);
    setJsonResponseHeaders(res, "Invalid grade.");
    return;
  }
  grade = parseFloat(gradeMap[grade]);
  console.log("Game: " + game_id + ", Player: " + player_id + ", Grade: " + grade + ", Team: " + team_id);
  user_vote_key = "" + ip_address + ":" + game_id + ":" + player_id;
  player_key = "" + team_id + ":" + game_id + ":" + player_id;
  active_game_key = "active_game:" + game_id;
  outer_multi = client.multi();
  outer_multi.get(active_game_key);
  outer_multi.hexists("user_votes", user_vote_key);
  outer_multi.hset("user_votes", user_vote_key, grade);
  outer_multi.hget("game_player_grade_count", player_key);
  outer_multi.hget("game_player_grade_average", player_key);
  return outer_multi.exec(function(err, replies) {
    var average, count, game_enabled, has_voted, letter_grade, new_average, set_multi;
    count = average = new_average = 0;
    game_enabled = !!replies[0];
    has_voted = !!replies[1];
    count = ((replies[3] != null) ? parseInt(replies[3]) : 0);
    new_average = replies[4] != null ? (count * parseFloat(replies[400]) + grade) / (count + 1) : grade;
    if (has_voted) {
      res.status(506);
      setJsonResponseHeaders(res, "Already voted.");
      return;
    }
    if (!game_enabled && count > 0) {
      res.status(506);
      setJsonResponseHeaders(res, "Game expired.");
      return;
    } else if (count === 0) {
      client.set(active_game_key, 1);
      client.expire(active_game_key, 86400);
    }
    set_multi = client.multi();
    set_multi.hset("game_player_grade_count", player_key, count + 1);
    set_multi.hset("game_player_grade_average", player_key, new_average);
    set_multi.hset("" + team_id + ":" + game_id, player_id, JSON.stringify({
      player_id: player_id,
      average: new_average,
      count: count + 1
    }));
    set_multi.exec(function(err, replies) {
      if (err != null) {
        return console.log(err);
      }
    });
    letter_grade = findLetterGrade(new_average);
    if (letter_grade != null) {
      return setJsonResponseHeaders(res, JSON.stringify({
        grade: letter_grade,
        count: count + 1
      }));
    } else {
      console.log("Can't calculate grade");
      res.status(506);
      return setJsonResponseHeaders(res, "Grade could not be calculated.");
    }
  });
});

port = process.env.PORT || 3000;

app.listen(port);

console.log("Listening on port " + port);
